#!/bin/zsh

function crlftolf()
{
	for i in $@; do
		dos2unix -n $i $i
	done
}

function copy()
{
    file=$1
    mime=$(file -b --mime-type $file)
    xclip -selection clipboard -t $mime $file
    echo "Copied file to clipboard!"
    command xclip < ${1}
    echo "Copied file ${1} to clipboard!"
}

function downmp3()
{
	yt-dlp -x --audio-format=mp3 -o ${PWD}/%(title)s.%(ext)s $@
}

function mnt-ms()
{
    udisksctl mount -b "${@}" -o dmask=022,fmask=133
}

function mnt-sec()
{
    encfs ~/Nextcloud/Secure ~/Secure "${@}"
}

function fastdel()
{
    uuid=".$(uuidgen)"
    mkdir $uuid
    rsync -a --delete $uuid/ $1/
    rmdir $uuid $1
}

function xmr-wallet()
{
    monero-wallet-cli \
        --config-file ~/.config/monero/wallet.conf \
        --wallet-file ~/Secure/crypto/xmr/xmr \
        "${@}"
}

function watchdirt()
{
    watch -x -t awk "/Dirty/||/Writeback:/{print}" /proc/meminfo
}

function viewkey()
{
    cat ${1} | gpg --import-options show-only --import
}
