#!/bin/sh

# Handy variables
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus

# lock config
export XSECURELOCK_FONT="Terminus"
export XSECURELOCK_PASSWORD_PROMPT=time_hex

export MOZ_DISABLE_RDD_SANDBOX=1

