#!/bin/sh

# Handy variables
export QT_QPA_PLATFORMTHEME=qt5ct
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export SDL_IM_MODULE=fcitx
export XMODIFIERS=@im=fcitx
export GLFW_IM_MODULE=ibus

# XDG Variables
export XDG_CURRENT_DESKTOP="i3"
export XDG_CONFIG_DIR="${HOME}/.config"

# lock config
export XSECURELOCK_FONT="Terminus"
export XSECURELOCK_PASSWORD_PROMPT=time_hex

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# Once running X
unset RTERM

eval $(gnome-keyring-daemon --start --components=secrets)

numlockx
xrdb ~/.Xresources

exec i3 &> ~/.local/share/xorg/i3.log
