#!/bin/zsh
alias history="history 0"
alias delet="shred -u -v"
alias free="free --si"
alias flog="journalctl -o cat -f -u"
#alias startx="startx >~/.local/share/xorg/startx.log 2>&1"
alias magnet2torrent="aria2c --bt-metadata-only --bt-save-metadata=true"
