program_options:
    udisks_version: 2
    tray: auto
    automount: false
    notify: true
    file_manager: pcmanfm

device_config:
    - id_type: exfat
      options: [dmask=022,fmask=133]
    - id_type: ntfs
      options: [dmask=022,fmask=133]
    - id_type: vfat
      options: [dmask=022,fmask=133]

notifications:
    device_mounted:   5    
    device_unmounted: false
    device_added:     false
    device_removed:   false
    device_unlocked:  -1   
    device_locked:    -1   
    job_failed:       -1   
